name: lograt
description: "Keep track of all your strength training numbers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_migration: ^0.3.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  uuidv7: ^1.0.0
  collection: ^1.19.1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  sqflite_common_ffi: ^2.3.6
  mockito: ^5.4.6
  riverpod_generator: ^2.6.5
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#FDD835"
  image: assets/images/lograt_splash.png
  fullscreen: true
  android_12:
    color: "#FDD835"
    image: assets/images/lograt_splash_android12.png
    icon_background_color: "#FDD835"

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/lograt_icon.svg
    - assets/images/lograt_splash.png
    - assets/images/lograt_splash_android12.png